try {
  hello();
} catch (err) {
  console.log(err);
}

try {
  otrafun();
} catch {
  console.log("Mi propio err");
}
